services:
    traefik:
        image: traefik:v3.4
        container_name: traefik
        command:
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --entrypoints.web.address=:80
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped

    website-proxy:
        image: "ghcr.io/jeroenkool74/lan-party-local-website:latest"
        pull_policy: always
        volumes:
            - "${DOWNLOADS_PATH:-./downloads}:/usr/share/nginx/html/downloads:ro"
        labels:
            traefik.enable: "true"
            traefik.http.routers.website-proxy.rule: Host(`download.lan`) || Host(`downloads.lan`) || Host(`home.lan`)
            traefik.http.routers.website-proxy.entrypoints: web
            traefik.http.services.website-proxy.loadbalancer.server.port: "80"
